ddp:
  ddp_enable: False
  world_size: 1
  gpus: [0]
  
model:
  num_layers: 18
  weights_init: True

  depth_model: 'fusion'
  pose_model: 'fusion'
  
  fusion_level: 2
  fusion_feat_in_dim: 256
  use_skips: False
  
  voxel_unit_size: [1.0, 1.0, 1.5]
  voxel_size: [100, 100, 20]
  voxel_str_p: [-50.0, -50.0, -15.0]
  voxel_pre_dim: [64]
  proj_d_bins: 50
  proj_d_str: 2
  proj_d_end: 50

data:
  data_path: './input_data/DDAD/ddad_train_val/ddad.json' # 未被 synthetic 数据使用
  log_dir: './results/'
  dataset: 'synthetic'
  back_context: 1
  forward_context: 1
  depth_type: 'lidar'
  cameras: ['camera_01', 'camera_05', 'camera_06', 'camera_07', 'camera_08', 'camera_09']
  train_requirements: (gt_pose, mask)
  val_requirements: (gt_pose, gt_depth, mask)
  synthetic_length: 16
  synthetic_seed: 123
  synthetic_radius: 5.0
  synthetic_height: 1.6

training:
  height: 384
  width: 640
  scales: [0]
  frame_ids: [0, -1, 1]
  
  batch_size: 2
  num_workers: 8
  learning_rate: 0.0001
  num_epochs: 5
  scheduler_step_size: 1

  min_depth: 1.5
  max_depth: 200.0

  spatio: True
  spatio_temporal: True

  intensity_align: True
  focal_length_scale: 300

  aug_depth: False
  aug_angle: [15, 15, 40]

loss:
  disparity_smoothness: 0.001
  spatio_coeff: 0.03
  spatio_tempo_coeff: 0.1
  pose_loss_coeff: 0.0
  
eval:
  eval_batch_size: 1
  eval_num_workers: 0
  eval_min_depth: 0
  eval_max_depth: 200
  eval_visualize: False
  syn_visualize: False
  syn_idx: 5
  
load:
  pretrain: False
  weights: 'weights_00'
  models_to_load: ['depth_net']
  
logging:
  early_phase: 10
  log_frequency: 1
  late_log_frequency: 50
  save_frequency: 1
